export const BANK_ERROR_CODES = {
  "12": "Invalid Transaction (Bene/Remitter decline)",
  "65": "Transaction frequency exceeded for account",
  "94": "Duplicate Transaction",
  "MJ": "Invalid beneficiary IFSC or NBIN",
  "ERR01": "Invalid transaction type",
  "ERR02": "Invalid date time in request",
  "ERR03": "Invalid Merchant id",
  "ERR04": "Blank trace number",
  "ERR06": "Invalid beneficiary mobile number",
  "ERR08": "Invalid beneficiary IFSC code",
  "ERR13": "Duplicate trace id",
  "ERR14": "Invalid queryback trace number",
  "ERR16": "Transaction not allowed above 5000 INR",
  "ERR18": "Invalid remitter name",
  "19": "Duplicate reference number",
  "20": "Invalid Response Code",
  "42": "Card-Issuer inoperative",
  "52": "Invalid Account",
  "78": "Transfer limit exceeded",
  "84": "Block operation failed (Account closed/frozen)",
  "92": "Invalid IFSC",
  "96": "System Malfunction",
  "98": "System malfunction",
  "M1": "Invalid Account Number or IFSC Code",
  "M2": "Amount limit Exceeded",
  "M3": "Account Blocked/Frozen",
  "M4": "NRE Account",
  "M5": "Account Closed",
  "M6": "Limit exceeded for member bank",
  "M7": "Transaction not permitted for this Account",
  "M8": "Transaction limit exceeded for this Account",
  "MP": "Missing Parameter",
  "N51": "Transaction unsuccessful due to issue at beneficiary bank",
  "NC": "No connectivity with NPCI",
  "RM1": "Invalid Remitter Mobile Number/MMID",
  "RM4": "Remitter Account is NRE Account",
  "RM7": "Fund transfer between Kotak accounts not available via IMPS",
  "WC": "Check Sum Error",
  "ERR05": "Invalid request type",
  "ERR07": "Invalid beneficiary MMID",
  "ERR09": "Invalid beneficiary account number",
  "ERR10": "Invalid amount",
  "ERR11": "Invalid checksum",
  "ERR15": "No such transaction request enquiry",
  "ERR17": "Invalid sender mobile number",
  "03": "Invalid scheme type",
  "04": "Insufficient funds",
  "08": "CBS Offline",
  "13": "Transaction Amount cannot be zero",
  "T-001": "Invalid Request - Check HTTP method/URL/Data",
  "T-002": "Unauthorized Request - SrcAppCd and IP mismatch",
  "76": "Card-Issuer timed out",
  "RET": "Return",
  "00": "Successful Transaction",
  "ERR12": "Invalid response from IMPS switch",
  "91": "Transaction Timeout",
  "M0": "Verification Successful but original credit failed",
  "MS": "Transaction declined as invalid account number",
  "T-003": "Technical error - contact support",
  "TCC": "Deemed Approved",
  "FRE": "Return",
  "59": "Suspected fraud decline",
  "30": "Invalid Message",
  "01": "Invalid Transaction",
  "02": "Format error",
  "06": "Subprogram error",
  "22": "Transaction not allowed - amount exceeds limit",
  "24": "Insufficient balance in pool account",
  "51": "Not sufficient funds",
  "56": "Invalid Account Type",
  "57": "Transaction not permitted to account",
  "61": "Exceeds account limit",
  "77": "Suspected fraud - based on risk score",
  "86": "Invalid NBIN",
  "99": "Transaction not permitted",
  "E15": "Invalid response code",
  "M57": "Transaction not permitted to Merchant",
  "MA": "Merchant Validation Fail",
  "MC": "Bank not enabled for P2A functionality",
  "MF": "No response from merchant system",
  "MI": "Customer transaction limit exceeded",
  "MK": "Payee is individual, not merchant",
  "ML": "Payee is merchant, not individual",
  "MM1": "Invalid Merchant Mobile/MMID",
  "MM4": "Merchant Account is NRE",
  "MN": "Foreign inward remittance not allowed",
  "MQ": "Invalid payment reference",
  "MR": "Transaction amount less than RS.1",
  "MT": "General error - transaction not allowed",
  "MV": "Merchant online validation unavailable",
  "MW": "Foreign inward remittance for P2P only",
  "MX": "Invalid remitter bank Aadhaar",
  "NE": "NACK ERROR",
  "NR": "Invalid Service Provider configuration",
  "P2A92": "Invalid MMID / IFSC",
  "P2AM1": "Invalid Account Number or IFSC Code",
  "P2A_92": "Invalid IFSC or beneficiary bank unavailable",
  "UB": "Unable to process",
  "XC": "Invalid Transaction",
  "XD": "Invalid Amount field",
  "XF": "Invalid Message",
  "U88": "Connection timeout in credit request",
  "A01": "Payer account must be present",
  "B01": "Payees not present",
  "U01": "Duplicate request",
  "U02": "Amount cap exceeded",
  "U08": "System Exception",
  "U15": "Checksum failed",
  "U16": "Risk threshold exceeded",
  "U17": "Bank not registered",
  "U27": "No response from bank",
  "U31": "Credit failed",
  "U68": "Credit timeout",
  "U78": "Beneficiary bank offline",
  "U80": "Bank non responsive",
  "U86": "Remitter bank non responsive",
  "U89": "Beneficiary bank throttling decline",
  "U92": "Payer bank offline",
  "UP3": "Bank scheduled offline",
  "ZI": "Suspected fraud decline based on Risk score"
};

export const getBankErrorDescription = (code, defaultMessage = "Bank Verification Failed") => {
  if (!code) return defaultMessage;
  return BANK_ERROR_CODES[code] || defaultMessage;
};
